config/routes.rb
Rails.application.routes.draw do
  resources :charges
  resources :orders
  get 'my_cart', to: 'carts#show'
  resources :carts do
    collection do
      get :add_to
    end
    member do
      get :remove_from, :increment_num, :decrement_num
    end
  end
  resources :products
  resources :seller_profiles
  resources :enquiries
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller_profile.rb
class SellerProfile < ApplicationRecord
  belongs_to :user
  has_many :products

  validates :address, :suburb, :state, :postcode, :country, presence: true

  after_validation :geocode
  geocoded_by :full_address

  mount_uploader :logo, SellerProfileLogoUploader

  extend FriendlyId
  friendly_id :name, use: :slugged


  def full_address
    [address, suburb, state, postcode, country].join(', ')
  end

end

app/controllers/seller_profiles_controller.rb
class SellerProfilesController < ApplicationController
  before_action :set_seller_profile, only: [:show, :edit, :update, :destroy]

  # GET /seller_profiles
  # GET /seller_profiles.json
  def index
    @seller_profiles = SellerProfile.all
  end

  # GET /seller_profiles/1
  # GET /seller_profiles/1.json
  def show
    @product = Product.new
    @products = @seller_profile.products
  end

  # GET /seller_profiles/new
  def new
    @seller_profile = SellerProfile.new
  end

  # GET /seller_profiles/1/edit
  def edit
  end

  # POST /seller_profiles
  # POST /seller_profiles.json
  def create
    @seller_profile = SellerProfile.new(seller_profile_params)
    @seller_profile.user = current_user
    respond_to do |format|
      if @seller_profile.save
        format.html { redirect_to @seller_profile, notice: 'Seller profile was successfully created.' }
        format.json { render :show, status: :created, location: @seller_profile }
      else
        format.html { render :new }
        format.json { render json: @seller_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seller_profiles/1
  # PATCH/PUT /seller_profiles/1.json
  def update
    respond_to do |format|
      if @seller_profile.update(seller_profile_params)
        format.html { redirect_to @seller_profile, notice: 'Seller profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller_profile }
      else
        format.html { render :edit }
        format.json { render json: @seller_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seller_profiles/1
  # DELETE /seller_profiles/1.json
  def destroy
    @seller_profile.destroy
    respond_to do |format|
      format.html { redirect_to seller_profiles_url, notice: 'Seller profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller_profile
      @seller_profile = SellerProfile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_profile_params
      params.require(:seller_profile).permit(:user_id, :name, :bio, :logo, :address, :suburb, :state, :postcode, :country, :latitude, :longitude)
    end
end

app/helpers/seller_profiles_helper.rb
module SellerProfilesHelper
end

app/views/seller_profiles/_form.html.erb
<%= simple_form_for(@seller_profile) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">

  <%= f.input :name %>
  <%= f.input :bio %>
  <%= f.input :logo %>
  <%= f.input :address %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :suburb %>
    </div>
    <div class="col-md-4">
      <%= f.input :state, collection: ['NSW', 'ACT', 'QLD', 'WA', 'NT', 'SA', 'TAS'], prompt: 'State' %>
    </div>
    <div class="col-md-4">
      <%= f.input :postcode %>
    </div>
  </div>
  <%= f.input :country, priority: ['Australia'] %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/seller_profiles/edit.html.erb
<h1>Editing Seller Profile</h1>

<%= render 'form', seller_profile: @seller_profile %>

<%= link_to 'Show', @seller_profile %> |
<%= link_to 'Back', seller_profiles_path %>

app/views/seller_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seller Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Logo</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seller_profiles.each do |seller_profile| %>
      <tr>
        <td><%= seller_profile.user %></td>
        <td><%= seller_profile.name %></td>
        <td><%= seller_profile.bio %></td>
        <td><%= seller_profile.logo %></td>
        <td><%= seller_profile.address %></td>
        <td><%= seller_profile.suburb %></td>
        <td><%= seller_profile.state %></td>
        <td><%= seller_profile.postcode %></td>
        <td><%= seller_profile.country %></td>
        <td><%= seller_profile.latitude %></td>
        <td><%= seller_profile.longitude %></td>
        <td><%= link_to 'Show', seller_profile %></td>
        <td><%= link_to 'Edit', edit_seller_profile_path(seller_profile) %></td>
        <td><%= link_to 'Destroy', seller_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller Profile', new_seller_profile_path %>

app/views/seller_profiles/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Create Your Seller Profile</h1>
    <%= render 'form', seller_profile: @seller_profile %>
  </div>
</div>

app/views/seller_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <%= image_tag @seller_profile.logo_url, class: 'card-img-top' %>
      <div class="card-body">
        <h5 class="card-title"><%= @seller_profile.name %></h5>

      <p>
        <strong>Seller bio</strong><br>
        <%= @seller_profile.bio %>
      </p>
      <p>
        <strong>Address</strong><br>
        <%= @seller_profile.full_address %>
      </p>
      <p>
        <strong>Email</strong><br>
        <%= @seller_profile.user.email %>
      </p>
      <div id="map"></div>
      <% if @seller_profile == current_user.seller_profile %>
        <%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_seller_profile_path(@seller_profile), class: 'btn btn-primary' %>
      <% end %>
    </div>
    </div>
  </div>
  <div class="col-md-9">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      <i class="fa fa-plus-square"></i> Add Product
    </button>
    <hr>
    <div>
    <div id="product-list" class="card-deck">
      <%= render @products %>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'products/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

<script>
  function initMap() {
    var location = {lat: <%= @seller_profile.latitude %>, lng: <%= @seller_profile.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: location
    });
    var marker = new google.maps.Marker({
      position: location,
      map: map
    });
  }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAe3QzlfjbEspA62dwcX22kAmq2AdBovOs&callback=initMap">
</script>