config/routes.rb
Rails.application.routes.draw do
  resources :charges
  resources :orders
  get 'my_cart', to: 'carts#show'
  resources :carts do
    collection do
      get :add_to
    end
    member do
      get :remove_from, :increment_num, :decrement_num
    end
  end
  resources :products
  resources :seller_profiles
  resources :enquiries
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart, :optional => true
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  validates :name, :email, :address, :suburb, :state, :postcode, :country, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.cart = @cart
    @cart.cart_products.each do |cart_product|
      line_item = LineItem.create(product_id: cart_product.product.id, num: cart_product.num, price: cart_product.product.price)
      @order.line_items << line_item
    end
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :email, :address, :suburb, :state, :postcode, :country, :phone, :paid, :cart_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :address %>
    <%= f.input :suburb %>
    <%= f.input :state %>
    <%= f.input :postcode %>
    <%= f.input :country %>
    <%= f.input :phone %>
  </div>

  <div class="form-actions">
    <%= f.submit "Complete checkout", class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Paid</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.email %></td>
        <td><%= order.address %></td>
        <td><%= order.suburb %></td>
        <td><%= order.state %></td>
        <td><%= order.postcode %></td>
        <td><%= order.country %></td>
        <td><%= order.phone %></td>
        <td><%= order.paid %></td>
        <td><%= order.cart %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      <h1>Your Order</h1>
      <%= render 'form', order: @order %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h3>Your order</h3>
        <table class="table">
          <thead>
            <tr>
              <th>Product</th>
              <th class="text-center">Quantity</th>
              <th class="text-right">Price</th>
              <th class="text-right">Subtotal</th>
            </tr>
          </thead>
          <tbody>
            <% @cart.cart_products.each do |cart_product| %>
              <% product = cart_product.product %>
              <tr id="cart_product_row_<%= cart_product.id %>">
                <td>
                  <%= image_tag product.image_url, width: '100px' %>
                  <%= link_to product.name, product_path(product), target: '_blank' %>
                </td>
                <td class="text-center">
                  <span id="num-<%= cart_product.id %>"><%= cart_product.num %></span>
                </td>
                <td class="text-right"><%= number_to_currency(product.price) %></td>
                <td class="text-right" id="subtotal-<%= cart_product.id %>"><%= number_to_currency(cart_product.num * product.price) %></td>
              </tr>
            <% end %>
            <tr>
              <th colspan="3">TOTAL</th>
              <th class="text-right" id="cart-total"><%= number_to_currency(@cart.cart_value) %></th>
              <th></th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <p>
          <strong>Name:</strong>
          <%= @order.name %>
        </p>
        <p>
          <strong>Email:</strong>
          <%= @order.email %>
        </p>
        <p>
          <strong>Address:</strong>
          <%= @order.address %>,
          <%= @order.suburb %>, <%= @order.state %>, <%= @order.postcode %>, <%= @order.country %>
        </p>
        <p>
          <strong>Phone:</strong>
          <%= @order.phone %>
        </p>
        <hr>
        <form action="/charges" method="post" id="payment-form">
          <input name="utf8" type="hidden" value="&#x2713;"/>
          <%= hidden_field_tag :authenticity_token %>
          <input name="order_id" type="hidden" value="<%= @order.id %>"/>
          <div id="card-element" class="field" style="width:100%"></div>
          <div id="card-errors" role="alert" class="text-danger"></div>
          <button class="btn btn-success mt-2" id="submit-payment" type="submit">
            <span class="fa fa-lock"></span> Pay <%= number_to_currency(@order.cart.cart_value) %>
          </button>
        </form>
      </div>
    </div>
  </div>
</div>


<script src="https://js.stripe.com/v3/"></script>


<script>
    var stripe = Stripe('pk_test_3paUDa9xwnmHSs1XD9UmX3v3');
    var elements = stripe.elements();
    var style = {
      base: {
        color: '#303238',
        fontSize: '16px',
        lineHeight: '48px',
        fontSmoothing: 'antialiased',
        '::placeholder': {
          color: '#ccc',
        },
      },
      invalid: {
        color: '#e5424d',
        ':focus': {
          color: '#303238',
        },
      },
    };
    // Create an instance of the card Element
    var card = elements.create('card', {style: style, hidePostalCode: true});
    // Add an instance of the card Element into the `card-element` <div>
    card.mount('#card-element');
    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });
    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();
      function stripeTokenHandler(token) {
        var form = document.getElementById('payment-form');
        var submitButton = document.getElementById('submit-payment');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);
        form.submit();
        submitButton.innerHTML = '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>';
        submitButton.disabled = true;
      }
      stripe.createToken(card).then(function(result) {
        if (result.error) {
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
        } else {
          stripeTokenHandler(result.token);
        }
      });
    });
</script>