config/routes.rb
Rails.application.routes.draw do
  resources :charges
  resources :orders
  get 'my_cart', to: 'carts#show'
  resources :carts do
    collection do
      get :add_to
    end
    member do
      get :remove_from, :increment_num, :decrement_num
    end
  end
  resources :products
  resources :seller_profiles
  resources :enquiries
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  has_one :order

  before_create :generate_uuid

  def generate_uuid
    self.uuid = SecureRandom.hex(10)
  end

  def num_items
    self.cart_products.sum(:num)
  end

  def cart_value
    value = 0.0
    self.cart_products.each do |cp|
      value = value + (cp.num * cp.product.price)
    end
    return value
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :get_cart_product, only: [:increment_num, :decrement_num, :remove_from]

  def get_cart_product
    product = Product.find(params[:product_id])
    @cart_product = CartProduct.find_by(cart_id: @cart.id, product_id: product.id)
  end

  def increment_num
    @cart_product.increment_num
    
  end

  def decrement_num
    @cart_product.decrement_num
  end

  def remove_from


    @cart.products.delete(product)
    if @cart.products.count == 0
      @cart.destroy
      @cart_destroyed = true
    end
  end

  def add_to
    @product = Product.find(params[:product_id])
    unless @cart
      @cart = Cart.create!
      cookies[:cart_uuid] = @cart.uuid
    end
    if @cart.products.include?(@product)
      cart_product = CartProduct.find_by(cart_id: @cart.id, product_id: @product.id)
      cart_product.increment_num
    else
      @cart.products << @product
    end
  end

  def show
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/add_to.js.erb
<% message = @product.name + " has been added to your cart." %>
$('#cart').html('<%= j render partial: "layouts/cart", locals: { message: message } %>');
$('#cart').slideDown('fast');
$('#cart-num-items').html("<%= j render partial: 'layouts/cart_num_items', locals: { cart: @cart } %>");
$('#cart-num-items').slideDown('fast');

app/views/carts/increment_num.js.erb
$('#cart-num-items').html("<%= j render partial: 'layouts/cart_num_items', locals: { cart: @cart } %>");
$('#cart-total').html('<%= number_to_currency(@cart.cart_value) %>');
$('#num-<%= @cart_product.id %>').html('<%= @cart_product.num %>');
$('#subtotal-<%= @cart_product.id %>').html('<%= number_to_currency(@cart_product.num * @cart_product.product.price) %>');

app/views/carts/remove_from.js.erb
$('#cart_product_row_<%= @cart_product.id %>').slideUp('fast');
$('#cart-num-items').html("<%= j render partial: 'layouts/cart_num_items', locals: { cart: @cart } %>");
$('#cart-total').html('<%= number_to_currency(@cart.cart_value) %>');

app/views/carts/show.html.erb
<h1>My Cart</h1>

<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th class="text-center">Quantity</th>
      <th class="text-right">Price</th>
      <th class="text-right">Subtotal</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_products.each do |cart_product| %>
      <% product = cart_product.product %>
      <tr id="cart_product_row_<%= cart_product.id %>">
        <td>
          <%= image_tag product.image_url, width: '100px' %>
          <%= link_to product.name, product_path(product), target: '_blank' %>
        </td>
        <td class="text-center">
          <span id="num-<%= cart_product.id %>"><%= cart_product.num %></span>
          <%= link_to '+', increment_num_cart_path(@cart, product_id: product.id), class: 'btn btn-outline-info btn-sm', remote: true %>
          <% if cart_product.num > 1 %>
            <%= link_to '-', decrement_num_cart_path(@cart, product_id: product.id), class: 'btn btn-outline-info btn-sm', remote: true %>
          <% end %>
        </td>
        <td class="text-right"><%= number_to_currency(product.price) %></td>
        <td class="text-right" id="subtotal-<%= cart_product.id %>"><%= number_to_currency(cart_product.num * product.price) %></td>
        <td><%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, remove_from_cart_path(@cart, product_id: product.id), class: 'text-danger', remote: true %></td>
      </tr>
    <% end %>
    <tr>
      <th colspan="3">TOTAL</th>
      <th class="text-right" id="cart-total"><%= number_to_currency(@cart.cart_value) %></th>
      <th></th>
    </tr>
  </tbody>
</table>

<div class="text-right">
  <%= link_to 'Checkout', new_order_path, class: 'btn btn-success btn-lg' %>
</div>