config/routes.rb
Rails.application.routes.draw do
  resources :charges
  resources :orders
  get 'my_cart', to: 'carts#show'
  resources :carts do
    collection do
      get :add_to
    end
    member do
      get :remove_from, :increment_num, :decrement_num
    end
  end
  resources :products
  resources :seller_profiles
  resources :enquiries
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller_profile
  has_many :cart_products, dependent: :destroy
  has_many :carts, through: :cart_products
  has_many :line_items, dependent: :destroy
  has_many :orders, through: :line_items

  validates :name, :description, :price, :num_in_stock, presence: true
  validates :price, :num_in_stock, numericality: { greater_than_or_equal_to: 0 }

  mount_uploader :image, ProductImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.seller_profile = current_user.seller_profile
    respond_to do |format|
      if @product.save
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to seller_profile_path(@product.seller_profile), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:seller_profile_id, :name, :description, :image, :price, :num_in_stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :price %>
    <%= f.input :num_in_stock %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="card">
  <a href="<%= product_path(product) %>"><img class="card-img-top" src="<%= product.image_url %>" alt="Card image cap"></a>
  <div class="card-body">
    <h4 class="card-title">
      <%= link_to product.name, product %>
    </h4>
    <p class="card-text"><%= product.description %></p>
    <p class="card-text">
      <small class="text-muted"><%= number_to_currency(product.price) %> </small>
      <span class="badge badge-secondary"><%= product.num_in_stock %> in stock</span>
      <%= link_to 'Add to cart', add_to_carts_path(product_id: product.id), class: 'btn btn-success', remote: true %>
    </p>
  </div>
  <% if user_signed_in? %>
    <% if current_user == product.seller_profile.user %>
    <div class="card-footer text-muted">
      <%= link_to '<i class="fa fa-edit"></i> EDIT'.html_safe, edit_product_path(product) %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/products/create.js.erb
$('#product-list').prepend('<%= j render @product %>');
$('#exampleModal').modal('hide');

// Make title of product a link to the product show page
// Make product show page pretty
// Show price and num_in_stock in each product card

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Seller profile</th>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price</th>
      <th>Num in stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.seller_profile %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image %></td>
        <td><%= product.price %></td>
        <td><%= product.num_in_stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render @product %>

  </div>
</div>